const HeaderActionTypes = {
    TOGGLE_ARRIVAL_HIDDEN: "TOGGLE_ARRIVAL_HIDDEN",
    TOGGLE_MEN_HIDDEN: "TOGGLE_MEN_HIDDEN",
    TOGGLE_WOMEN_HIDDEN: "TOGGLE_WOMEN_HIDDEN",
    TOGGLE_KID_HIDDEN: "TOGGLE_KID_HIDDEN",
    TOGGLE_LIFESTYLE_HIDDEN: "TOGGLE_LIFESTYLE_HIDDEN",
    TOGGLE_BRAND_HIDDEN: "TOGGLE_BRAND_HIDDEN",
}

export default HeaderActionTypes;